apiVersion: v1
kind: Namespace
metadata:
  name: unifiappay
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: unifiappay
type: Opaque
stringData:
  POSTGRES_PASSWORD: unifiap-pass
  POSTGRES_USER: unifiap
  POSTGRES_DB: unifiap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: unifiappay
data:
  APP_ENV: "production"
  APP_NAME: "unifiap-pay-api"
